default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ["--diff"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.2
    hooks:
      - id: isort
        args: ["--diff"]
        additional_dependencies: [toml]
        files: \.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4  # do not update this until our CI runner uses Python >=3.8.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^tests/
        verbose: true
        args: [--show-error-codes]
        additional_dependencies: ['types-click', 'types-requests', 'types-PyYAML', 'types-cryptography', 'types-setuptools']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
